### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [Lenart12/ice.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by Lenart12** [comment]
Sorry for the late reply, didn't notice your request. I have added a MIT license per your wish so if you still wish to add this feel free to do it.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/800
